### ISSUE TITLE
it does not generate videos

### ISSUE THREAD

**Issue by Anayat-ullah** [muazhurani/mesk-ulkhitam#1]
it gives me this when I click genrate video
 Traceback (most recent call last):
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\app.py", line 84, in generate_video
    image_clip = ImageClip(image_path, duration=audio_clip.duration).set_opacity(0.7).resize(newsize=resolution)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\moviepy\video\fx\resize.py", line 152, in resize
    newclip = clip.fl_image(fl)
              ^^^^^^^^^^^^^^^^^
  File "<decorator-gen-72>", line 2, in fl_image
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\moviepy\video\VideoClip.py", line 936, in fl_image
    arr = image_func(self.get_frame(0))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\moviepy\video\fx\resize.py", line 150, in <lambda>
    fl = lambda pic: resizer(pic.astype('uint8'), newsize)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anayat-PC\Desktop\misk\mesk-ulkhitam-main\.venv\Lib\site-packages\moviepy\video\fx\resize.py", line 37, in resizer
    resized_pil = pilim.resize(newsize[::-1], Image.ANTIALIAS)
                                              ^^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'[
![Screenshot (25)](https://github.com/muazhurani/mesk-ulkhitam/assets/131428972/30875424-f7c4-4714-9d2a-317e95f473be)
](url)

**Comment by Anayat-ullah** [comment]
I solved it my self there was a problem in file named resize so chat gpt gave me the correcrt code nd it worked
